#!/bin/bash
#skript algab
echo "pühapäev - 0, esmaspäev - 1... laupäev -6"
echo "sisesta millal ära sõidad:"
read sa
echo "sisesta reisi ööpäevade arv."
read op
rpv=$(($op % 7)) 
tg=$(($sa + $rpv))
echo "tagasi oled $tg päeval"
#skripti lõpp
