#!/bin/bash
#
# kasutajate nimekiri kujul Perenimi, Eesnimi
#
# skripti algus
#
who | cut -f1 -d" " | cut -f2 -d"." > Saget # lõikame perenimi - see on 2. element peale punkti ja salvestame faili
who | cut -f1 -d" " | cut -f1 -d"." > Bob # lõikame eesnimi - see on 1. element ennem punkti ja salvestame faili
paste -d"." Saget Bob > nimed # kleebime need failid vastavas järjekorras kokku 
cat nimed | sort | uniq # sorteerime väljund ja võtame korduvad välja
#
# skripti lõpp
