#!/bin/bash
#
#
echo "Janar Paas"
echo "ISP117"
echo "suht lahe aine, aga natuke keeruline"
echo "edasi jõuab normaalselt, kui midagi ei oska saab alati teiste käest küsida, midagi muud nagu öelda ei ole"
