#! /bin/bash
#
#
#skripti algus                                                  dab
echo "Tere, sisesta ome ees- ja perenimi"
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perenimi on $perenimi"

